name: FastAPI CI/CD

on:
  push:
    branches: 
      - main 

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:   
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install Python Virtual ENV
        run: pip install virtualenv

      - name: Cache Virtual ENV
        uses: actions/cache@v2
        with:
          path: venv
          key: ${{ runner.os }}-venv-${{ hashFiles('**/requirements*.txt') }}-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-venv-

      - name: Install Dependencies
        run: |
          python -m venv venv
          . venv/bin/activate
          pip install --no-cache-dir -r requirements.txt

      - name: Run Tests
        run: |
          . venv/bin/activate
          pytest

      - name: Create Archive of Dependencies
        run: |
          cd venv/lib/python3.8/site-packages
          zip -r9 ../../../../api.zip .
          cd -
          zip -g api.zip main.py
          zip -g api.zip -r api/
          zip -g api.zip -r app/

      - name: Upload Zip File Artifact
        uses: actions/upload-artifact@v4
        with:
          name: api
          path: api.zip

  CD:
    runs-on: ubuntu-latest
    needs: CI
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    steps:
      - name: Install AWS CLI
        uses: unfor19/install-aws-cli-action@v1
        with:
          version: 1
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}

      - name: Download Lambda api.zip
        uses: actions/download-artifact@v4
        with:
          name: api

      - name: Upload to S3
        run: aws s3 cp api.zip s3://fastapi-vendor/api.zip
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}

      - name: Deploy New Lambda
        run: aws lambda update-function-code --function-name fastapi-vendor --s3-bucket fastapi-vendor --s3-key api.zip
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
